proyecto_tienda/ofertas/urls.py
from django.urls import path
from . import views

app_name='ofertas'

urlpatterns = [
    path('', views.index, name='index'),
    path('crear_oferta/', views.crear_oferta, name='crear_oferta'),
    path('editar_oferta/<int:oferta_id>/', views.editar_oferta, name='editar_oferta'),
    path('eliminar_oferta/<int:oferta_id>/', views.eliminar_oferta, name='eliminar_oferta'),
]

proyecto_tienda/productos/urls.py
from django.urls import path
from . import views

app_name='productos'

urlpatterns= [
    path('', views.index, name='index'),
]

proyecto_tienda/proyecto_tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include ('productos.urls')),
    path('ofertas/', include(('ofertas.urls', 'ofertas'), namespace='ofertas')), #agregué 'ofertas' y el namespace para que encuentre bien la ruta
    path('', views.index, name='index'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
]

proyecto_tienda/ofertas/models.py
from django.db import models
from django.forms import ValidationError
from productos.models import Producto

# Create your models here.

class Oferta(models.Model):
    producto=models.ForeignKey(Producto, on_delete=models.CASCADE)
    porcentaje_descuento=models.DecimalField(max_digits=5, decimal_places=2)
    fecha_inicio=models.DateTimeField(null=False, blank=False)
    fecha_fin=models.DateTimeField(null=False, blank=False)
    
    #metodo especial para validaciones personalizadas en django (en este caso para fecha de inicio y porcentaje de descuento válidos)
    def clean(self): 
        if self.fecha_inicio>=self.fecha_fin:
            raise ValidationError("La fecha de inicio debe ser anterior a la de culminación") 
        if self.porcentaje_descuento<0 or self.porcentaje_descuento>100:
            raise ValidationError("El porcentaje de descuento debe estar entre 0% y 100%")
    
    #Llama a clean antes de guardar los datos en la bbdd y que los verifique previamente.    
    def save(self, *args, **kwargs):  #permite recibir cualquier argumento adicional necesario
        self.clean()
        super(Oferta, self).save(*args, **kwargs)
    
    #Este string se muestra en el panel de admin:
    def __str__(self):
        return f"Oferta en {self.producto.nombre} - {self.porcentaje_descuento}% de descuento" 
    
    #Calcula el precio de oferta:
    @property
    def precio_oferta(self):
        return self.producto.precio*(1-(self.porcentaje_descuento/100))
    
    

proyecto_tienda/productos/models.py
from django.db import models

# Create your models here.       #acá creamos las tablas Categoría y Producto
class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nombre
    

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    categoria =  models.ForeignKey (Categoria, on_delete=models.CASCADE)      
    
    def __str__(self):
        return self.nombre
    
    

proyecto_tienda/ofertas/forms.py
from django import forms
from .models import Oferta

class OfertaForm(forms.ModelForm):
    fecha_inicio=forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type':'datetime-local'}), input_formats=['%d-%m-%YT%H:%M'])
    fecha_fin=forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type':'datetime-local'}), input_formats=['%d-%m-%YT%H:%M'])
    class Meta:
        model= Oferta
        fields= ['producto', 'porcentaje_descuento', 'fecha_inicio', 'fecha_fin']

proyecto_tienda/ofertas/views.py
from datetime import datetime
from django.shortcuts import render, redirect, get_object_or_404
from .models import Oferta
from .forms import OfertaForm
from django.contrib.auth.decorators import login_required, permission_required


# Create your views here.
def index(request):
    current_date=datetime.now()
    ofertas=[]
    
    try:
        ofertas=Oferta.objects.filter(fecha_inicio__lte=current_date, fecha_fin__gte=current_date) 
#        raise Exception("Simulación de error inesperado")  #Esta línea se hizo para probar que el 
#error inesperado del bloque try except está funcionando, debe mantenerse comentada.
        if not ofertas:
            raise ValueError("No hay ofertas disponibles en este momento")
    except ValueError as e:
        #Manejo de error específico (no hay ofertas)
        return render(request, 'ofertas/index.html', {'error': str(e), 'current_date': current_date})
    except Exception as e:
        #Manejo de cualquier otro error
        return render(request, 'ofertas/index.html', {'error': 'Se produjo un error inesperado!', 'current_date': current_date})
    
    context={
#        'is_special_offer': False  #Se Cambia a True para si y False para no (para que aparezca si o no)        
        'current_date':current_date,
        'ofertas':ofertas
    }
    return render(request, 'ofertas/index.html', context)



@login_required()
@permission_required('ofertas.add_oferta', raise_exception=True)
#funcion para el formulario de ofertas
def crear_oferta(request):
    if request.method=='POST':
        form=OfertaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ofertas:index')
    else:
        form=OfertaForm()
    return render(request, 'ofertas/crear_oferta.html', {'form':form})

@login_required()
@permission_required('ofertas.change_oferta', raise_exception=True)
def editar_oferta(request, oferta_id):
    oferta= get_object_or_404(Oferta, id=oferta_id)
    if request.method == 'POST':
        form=OfertaForm(request.POST, instance=oferta)
        if form.is_valid():
            form.save()
            return redirect('ofertas:index')
    else:
        form=OfertaForm(instance=oferta)    
    return render(request, 'ofertas/crear_oferta.html', {'form':form}) #Crear html de editar oferta y de eliminar oferta

@login_required()
@permission_required('ofertas.delete_oferta', raise_exception=True)
def eliminar_oferta(request, oferta_id):
    oferta = get_object_or_404(Oferta, id=oferta_id)
    if request.method=='POST':
        oferta.delete()
        return redirect('ofertas:index')
    return render(request, 'ofertas/eliminar_oferta.html', {'oferta':oferta}) 
    


    

proyecto_tienda/productos/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.
def index(request):
    productos = Producto.objects.all()
    return render(request, 'productos/index.html', {'productos': productos})

proyecto_tienda/proyecto_tienda/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')#renderiza la plantilla index.html

proyecto_tienda/ofertas/templates/ofertas/crear_oferta.html
<!--ruta ofertas/crear_oferta-->
{% extends 'base.html' %}

{% block title %}Crear Oferta{% endblock %}

{% block content %}
<h1>Crear Nueva Oferta</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear Oferta</button>
</form>


{% endblock%}

proyecto_tienda/ofertas/templates/ofertas/eliminar_oferta.html
<!--ruta ofertas/eliminar_oferta-->
{% extends 'base.html' %}

{% block title %}Eliminar Oferta{% endblock %}

{% block content %}
<h1>Eliminar Oferta</h1>
<p>¿Está seguro de eliminar la oferta para {{oferta.producto.nombre}}?</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-secondary bg-danger">Eliminar Oferta</button>
</form>
<br>
<a href="{% url 'ofertas:index' %}">Volver a Ofertas</a>
{% endblock%}

proyecto_tienda/ofertas/templates/ofertas/index.html
{% extends 'base.html'%}

{%block title%}Ofertas{% endblock %}

{% block content %}
<header class="text-center">
    <h1>OFERTAS</h1>
</header>    
<p class="lead text-center">Consulta nuestras últimas ofertas en la tienda.</p>
<!--    <p>¿Hay una oferta especial? {{is_special_offer|yesno:"Sí,No"}}</p> se comentó en views también-->
<p>Fecha de hoy: {{ current_date|date:"d-m-Y" }}</p>
{% if error%}
    <div class="alert alert-danger">{{error}}</div>
{% endif %}
{% if ofertas %}
<div class="container">
    <h2>Productos en Oferta</h2>
    <table >
        <thead>
            <tr>
                <th>Producto</th>
                <th>Precio Original</th>
                <th>Descuento (%)</th>
                <th>Precio con Descuento</th>
            </tr>
        </thead>
        <tbody>
            {% for oferta in ofertas %}
                <tr>
                    <td>{{ oferta.producto.nombre }}</td>
                    <td>$ {{ oferta.producto.precio|floatformat:1 }}</td>
                    <td>{{ oferta.porcentaje_descuento }}%</td>
                    <td>$ {{ oferta.precio_oferta|floatformat:1 }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>No hay ofertas disponibles actualmente</p>
{% endif %}
</div>
{% endblock %}

proyecto_tienda/productos/templates/productos/index.html
{% extends 'base.html'%}

{%block title%}Productos{% endblock %}

{%block content%}
<header class="text-center">
    <h1>Lista de Productos</h1>
</header>    
    <nav>
        <a href="{% url 'index' %}">Home</a>
        <a href="{% url 'ofertas:index' %}">Ir a Ofertas</a>
    </nav>

    <div class="container">
        <table>
            <thead>
                <tr>
                    <th>NOMBRE</th>
                    <th>PRECIO</th>
                    <th>CATEGORIA</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in productos %}
                    <tr>
                        <td>{{ producto.nombre }}</td>
                        <td>{{ producto.precio }}</td>
                        <td>{{ producto.categoria.nombre }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3">
                            <h4>No hay productos</h4>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
    {% endblock %}
   

proyecto_tienda/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block title %}Principal{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">Mi Tienda</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNav" aria-controls="navbarNav"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'productos:index'  %}">Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ofertas:index' %}">Ofertas</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    <!--Contenido Principal-->
    <div class="container mt-4">
        {% block content %} {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js'%}"></script>
</body>
</html>

proyecto_tienda/templates/index.html
{% extends 'base.html'%}

{% block title %} Página Principal {% endblock %}

{% block content%}

<header class="text-center">
    <h1>PÁGINA PRINCIPAL</h1>
</header>

<div class="jumbotron bg-light p-5 rounded mt-4">
    <div class="row"> 
        <div class="col-lg-8 col-md-10 col-sm-12 mx-auto text-center">
            <h2 class="display-4">Bienvenido a Nuestra Tienda</h2>
            <p class="lead">Explora nuestra selección de productos y ofertas</p>
            <hr class="my-4">
            <p>Haz clic en los enlaces de arriba para ir a nuestras categorías</p>
            <button id="show-alert" class="btn btn-warning btn-lg btn-block">Presiona Aquí</button>
        </div>
    </div>
</div>
<nav class="text-center">
    <a class="btn btn-primary" href="{% url 'productos:index' %}">IR A PRODUCTOS</a>
    <a class="btn btn-secondary" href="{% url 'ofertas:index' %}">IR A OFERTAS</a>
</nav>
{% endblock %}